//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BundleTransformer.MicrosoftAjax.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BundleTransformer.MicrosoftAjax.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End column.
        /// </summary>
        public static string ErrorDetails_EndColumn {
            get {
                return ResourceManager.GetString("ErrorDetails_EndColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End line.
        /// </summary>
        public static string ErrorDetails_EndLine {
            get {
                return ResourceManager.GetString("ErrorDetails_EndLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code.
        /// </summary>
        public static string ErrorDetails_ErrorCode {
            get {
                return ResourceManager.GetString("ErrorDetails_ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string ErrorDetails_File {
            get {
                return ResourceManager.GetString("ErrorDetails_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help keyword.
        /// </summary>
        public static string ErrorDetails_HelpKeyword {
            get {
                return ResourceManager.GetString("ErrorDetails_HelpKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string ErrorDetails_Message {
            get {
                return ResourceManager.GetString("ErrorDetails_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity.
        /// </summary>
        public static string ErrorDetails_Severity {
            get {
                return ResourceManager.GetString("ErrorDetails_Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start column.
        /// </summary>
        public static string ErrorDetails_StartColumn {
            get {
                return ResourceManager.GetString("ErrorDetails_StartColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start line.
        /// </summary>
        public static string ErrorDetails_StartLine {
            get {
                return ResourceManager.GetString("ErrorDetails_StartLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategory.
        /// </summary>
        public static string ErrorDetails_Subcategory {
            get {
                return ResourceManager.GetString("ErrorDetails_Subcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During minification of {0}-code by Microsoft Ajax Minifier, readed from the file {1}, error has occurred..
        /// </summary>
        public static string Minifiers_MicrosoftAjaxMinificationFailed {
            get {
                return ResourceManager.GetString("Minifiers_MicrosoftAjaxMinificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During minification of {0}-code by Microsoft Ajax Minifier syntax error has occurred. 
        ///See more details:
        ///
        ///{2}.
        /// </summary>
        public static string Minifiers_MicrosoftAjaxMinificationSyntaxError {
            get {
                return ResourceManager.GetString("Minifiers_MicrosoftAjaxMinificationSyntaxError", resourceCulture);
            }
        }
    }
}
